language: node_js
node_js:
 - '6'
 - '8'
 - '10'
 - '12'
 - 'node'
install:
 - npm install
 - typings install
script:
 - npm run lint
 - npm run build
 - npm test
# before_deploy:
#  - npm run typedoc
# deploy:
#   skip_cleanup: true
#   provider: surge
#   project: ./typedoc/
#   domain: typed-mysql.surge.sh
